import { CrispProvider } from "@/components/CrispProvider";
import { Toaster } from "@/components/ui/toaster";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import ReactReduxProvider from "./ReactReduxProvider";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ReactReduxProvider>
      <html lang="en">
        <body className={inter.className} suppressHydrationWarning={true}>
          {children}
          <Toaster />
        </body>
      </html>
    </ReactReduxProvider>
  );
}
